language: python

python:
    - 3.3
    - 3.4

env:
    matrix:
        - PYTHONASYNCIODEBUG=1
        - PYTHONASYNCIODEBUG=0

matrix:
   include:
     - addons:
        mariadb: 5.5
     - addons:
        mariadb: 10.0
     - addons:
        mariadb: 10.1


before_script:
    - "mysql -e 'DROP DATABASE IF EXISTS test_pymysql; create database test_pymysql  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - "mysql -e 'DROP DATABASE IF EXISTS test_pymysql2; create database test_pymysql2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"

install:
    - pip install flake8
    - pip install sqlalchemy
    - pip install nose
    - pip install coverage
    - pip install .
    - pip install coveralls

script:
- make cov
# checking examples
- >
  for example in $(find $PWD/examples/ -name "*.py"); do
  echo "Running ${example}";
  python3 ${example} || exit 1;
  done;

after_success:
  - coveralls
